
#data00
traveldata<-raw_data
traveldata$Departure.Delay.in.Minutes <- ifelse(is.na(traveldata$Departure.Delay.in.Minutes) & traveldata$Flight.cancelled == "Yes", 9999, traveldata$Departure.Delay.in.Minutes)
traveldata$Arrival.Delay.in.Minutes <- ifelse(is.na(traveldata$Arrival.Delay.in.Minutes) & traveldata$Flight.cancelled == "Yes", 9999, traveldata$Arrival.Delay.in.Minutes)
traveldata$Flight.time.in.minutes <- ifelse(is.na(traveldata$Flight.time.in.minutes) & traveldata$Flight.cancelled == "Yes", 9999, traveldata$Flight.time.in.minutes)
traveldatacleaned<- traveldata[-(is.na(traveldata$Arrival.Delay.in.Minutes)),] 
traveldatacleaned<- na.omit(traveldata) 
traveldatacleaned$Satisfaction<-as.numeric(traveldatacleaned$Satisfaction)
summary(traveldata)
###############################################################################
#modelOfLoyalty<-lm(formula = Satisfaction~No..of.other.Loyalty.Cards,data = traveldatacleaned)
#summary(modelOfLoyalty)
#modelOfAirlineStatus<-lm(formula = Satisfaction~Airline.Status, data = traveldatacleaned)
#summary(modelOfAirlineStatus)
#lmCustomers <- lm(formula=Satisfaction~Age+Price.Sensitivity+Shopping.Amount.at.Airport+Eating.and.Drinking.at.Airport, data = traveldatacleaned)
#summary(lmCustomers)
#lmCustomers <- lm(formula=Satisfaction~Price.Sensitivity, data = traveldatacleaned)
#summary(lmCustomers)
#modelOfFTIM<-lm(formula = Satisfaction~Flight.time.in.minutes,data = traveldatacleaned)
#summary(modelOfFTIM)
#modelOfADDIM<-lm(formula = Satisfaction~Departure.Delay.in.Minutes+Arrival.Delay.in.Minutes,data = traveldatacleaned)
#summary(modelOfADDIM)
#modelOfDOM<-lm(formula = Satisfaction~Day.of.Month,data = traveldatacleaned)
#summary(modelOfDOM)
#modelOfQ<-lm(formula = Satisfaction~Shopping.Amount.at.Airport+Eating.and.Drinking.at.Airport,data = traveldatacleaned)
#summary(modelOfQ)
#modelOfClass<-lm(formula = Satisfaction~Class,data = traveldatacleaned)
#summary(modelOfClass)
#modelOfNOF<-lm(formula = Satisfaction~No.of.Flights.p.a.,data = traveldatacleaned)
#summary(modelOfNOF)
#modelOfNOF<-lm(formula = Satisfaction~No.of.Flights.p.a.,data = traveldatacleaned)
#summary(modelOfNOF)
#modelOfAge<-lm(formula = Satisfaction~Age,data = traveldatacleaned)
#summary(modelOfAge)
#modelOfGender<-lm(formula = Satisfaction~Gender,data = traveldatacleaned)
#summary(modelOfGender)

#modelOfFD<-lm(formula = Satisfaction~Flight.Distance,data = traveldatacleaned)
#summary(modelOfFD)
#modelOfALL<-lm(formula = Satisfaction~.,data = traveldatacleaned)
#summary(modelOfALL)
#modelOfCancelled<-lm(formula = Satisfaction~Flight.cancelled,data = traveldatacleaned)
#summary(modelOfCancelled)
#modelOfSDH<-lm(formula = Satisfaction~Scheduled.Departure.Hour,data = traveldatacleaned)
#summary(modelOfSDH)
#modelOfOC<-lm(formula = Satisfaction~Orgin.City,data = traveldatacleaned)
#summary(modelOfOC)
#modelOfOS<-lm(formula = Satisfaction~Origin.State,data = traveldatacleaned)
#summary(modelOfOS)
#modelOfDC<-lm(formula = Satisfaction~Destination.City,data = traveldatacleaned)
#summary(modelOfDC)
#modelOfDS<-lm(formula = Satisfaction~Destination.State,data = traveldatacleaned)
#summary(modelOfDS)
#modelOfFD<-lm(formula = Satisfaction~Flight.date,data = traveldatacleaned)
#summary(modelOfFD)
lmAll <- lm(formula=Satisfaction~Age+Price.Sensitivity+Shopping.Amount.at.Airport+Year.of.First.Flight+No.of.Flights.p.a.+No..of.other.Loyalty.Cards+Airline.Status+Type.of.Travel+Class+Scheduled.Departure.Hour+Arrival.Delay.greater.5.Mins, data = traveldatacleaned)
summary(lmAll)
lmDemoandCust <- lm(formula=Satisfaction~Age+Gender+Price.Sensitivity+Shopping.Amount.at.Airport+Eating.and.Drinking.at.Airport, data = traveldatacleaned)
summary(lmDemoandCust )
lmFlightexp <- lm(formula=Satisfaction~Year.of.First.Flight+No.of.Flights.p.a.+No..of.other.Loyalty.Cards+Airline.Status+Type.of.Travel+Class, data = traveldatacleaned)
summary(lmFlightexp)
lmFlighttimedetails <- lm(formula=Satisfaction~Scheduled.Departure.Hour+Departure.Delay.in.Minutes+Arrival.Delay.in.Minutes+Flight.time.in.minutes+Arrival.Delay.greater.5.Mins+Flight.Distance, data = traveldatacleaned)
summary(lmFlighttimedetails)

modelOfAS<-lm(formula = Satisfaction~Airline.Status,data = traveldatacleaned)
summary(modelOfAS)
##########################################################################################                 
#index <- 1:nrow(traveldatacleaned)
#testindex <- sample(index, trunc(length(index)/3))
#testset <- traveldatacleaned[testindex,]
#trainset <- traveldatacleaned[-testindex,]
#svm.model <- svm(Satisfaction ~ ., data = trainset, cost = 100, gamma = 1)
#svm.pred <- predict(svm.model, testset[,-10])


